import axios from 'axios'
import createPersistedState from "vuex-persistedstate";

export const plugins = [createPersistedState()]

export const state = () => ({
  isSidebarOpened: false,
  users: [
    {
      "id": 1,
      "name": "Project 1",
      "image": "1.jpg",
      "followers": 187,
      "plus": 7.4,
      "audience_quality": 81,
      "social_mentions": 714,
      "influencers": 425,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 2,
      "name": "Project 2",
      "image": "2.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 3,
      "name": "Project 3",
      "image": "3.jpg",
      "followers": 614,
      "plus": 1.7,
      "audience_quality": 91,
      "social_mentions": 824,
      "influencers": 652,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 4,
      "name": "Project 4",
      "image": "1.jpg",
      "followers": 916,
      "plus": 2.0,
      "audience_quality": 14,
      "social_mentions": 512,
      "influencers": 67,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 5,
      "name": "Project 5",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 6,
      "name": "Project 6",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 7,
      "name": "Project 7",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 8,
      "name": "Project 8",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 9,
      "name": "Project 9",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 10,
      "name": "Project 10",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 11,
      "name": "Project 11",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 12,
      "name": "Project 12",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 13,
      "name": "Project 13",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 14,
      "name": "Project 14",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 15,
      "name": "Project 15",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 16,
      "name": "Project 16",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 17,
      "name": "Project 17",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 18,
      "name": "Project 18",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 19,
      "name": "Project 19",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 20,
      "name": "Project 20",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 21,
      "name": "Project 21",
      "image": "1.jpg",
      "followers": 187,
      "plus": 7.4,
      "audience_quality": 81,
      "social_mentions": 714,
      "influencers": 425,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 22,
      "name": "Project 22",
      "image": "2.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 23,
      "name": "Project 23",
      "image": "3.jpg",
      "followers": 614,
      "plus": 1.7,
      "audience_quality": 91,
      "social_mentions": 824,
      "influencers": 652,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 24,
      "name": "Project 24",
      "image": "1.jpg",
      "followers": 916,
      "plus": 2.0,
      "audience_quality": 14,
      "social_mentions": 512,
      "influencers": 67,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 25,
      "name": "Project 25",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 26,
      "name": "Project 26",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 27,
      "name": "Project 27",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 28,
      "name": "Project 28",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 29,
      "name": "Project 29",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 30,
      "name": "Project 30",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 31,
      "name": "Project 31",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 32,
      "name": "Project 32",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 33,
      "name": "Project 33",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 34,
      "name": "Project 34",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 35,
      "name": "Project 35",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 36,
      "name": "Project 36",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 37,
      "name": "Project 37",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 38,
      "name": "Project 38",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 39,
      "name": "Project 39",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 40,
      "name": "Project 40",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 1,
      "name": "Project 1",
      "image": "1.jpg",
      "followers": 187,
      "plus": 7.4,
      "audience_quality": 81,
      "social_mentions": 714,
      "influencers": 425,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 2,
      "name": "Project 2",
      "image": "2.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 3,
      "name": "Project 3",
      "image": "3.jpg",
      "followers": 614,
      "plus": 1.7,
      "audience_quality": 91,
      "social_mentions": 824,
      "influencers": 652,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 4,
      "name": "Project 4",
      "image": "1.jpg",
      "followers": 916,
      "plus": 2.0,
      "audience_quality": 14,
      "social_mentions": 512,
      "influencers": 67,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 5,
      "name": "Project 5",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 6,
      "name": "Project 6",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 7,
      "name": "Project 7",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 8,
      "name": "Project 8",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 9,
      "name": "Project 9",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 10,
      "name": "Project 10",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 11,
      "name": "Project 11",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 12,
      "name": "Project 12",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 13,
      "name": "Project 13",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 14,
      "name": "Project 14",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 15,
      "name": "Project 15",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 16,
      "name": "Project 16",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 17,
      "name": "Project 17",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 18,
      "name": "Project 18",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 19,
      "name": "Project 19",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 20,
      "name": "Project 20",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 21,
      "name": "Project 21",
      "image": "1.jpg",
      "followers": 187,
      "plus": 7.4,
      "audience_quality": 81,
      "social_mentions": 714,
      "influencers": 425,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 22,
      "name": "Project 22",
      "image": "2.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 23,
      "name": "Project 23",
      "image": "3.jpg",
      "followers": 614,
      "plus": 1.7,
      "audience_quality": 91,
      "social_mentions": 824,
      "influencers": 652,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 24,
      "name": "Project 24",
      "image": "1.jpg",
      "followers": 916,
      "plus": 2.0,
      "audience_quality": 14,
      "social_mentions": 512,
      "influencers": 67,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 25,
      "name": "Project 25",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 26,
      "name": "Project 26",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 27,
      "name": "Project 27",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 28,
      "name": "Project 28",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 29,
      "name": "Project 29",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 30,
      "name": "Project 30",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 31,
      "name": "Project 31",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 32,
      "name": "Project 32",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 33,
      "name": "Project 33",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 34,
      "name": "Project 34",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 35,
      "name": "Project 35",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 36,
      "name": "Project 36",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 37,
      "name": "Project 37",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 38,
      "name": "Project 38",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 39,
      "name": "Project 39",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    },
    {
      "id": 40,
      "name": "Project 40",
      "image": "1.jpg",
      "followers": 276,
      "plus": 8.5,
      "audience_quality": 68,
      "social_mentions": 216,
      "influencers": 146,
      "discord": "/",
      "twitter": "/",
      "website": "/"
    }
  ],
  watchlist: [],
  search: ''
});

export const mutations = {
  showHideSidebar(state) {
    state.isSidebarOpened = !state.isSidebarOpened
  },
  SET_USERS: (state, users) => {
    state.users = users
  },
  SET_PAGINATED_USERS: (state, paginatedUsers) => {
    state.paginatedUsers = paginatedUsers
  },
  SEARCH_USERS: (state, search) => {
    state.search = search
  },
  ADD_TO_WATCHLIST: (state, watchList) => {
    state.watchlist = watchList
  }
}

export const getters = {
  USERS(state) {
    return state.users
  },
  WATCHLIST(state) {
    return state.watchlist
  }
}

export const actions = {
  // async GET_USERS({commit}) {
  //   axios.get('https://25c5-45-136-51-226.eu.ngrok.io/api/top', {
  //     'Access-Control-Allow-Credentials':true
  //   })
  //   .then((response) => {
  //     commit('SET_USERS', response.data)
  //   })
  // }
}
